// This file is auto-generated by scripts/set-env.js before build
// Do not edit manually - it will be overwritten during build
export const environment = {
  production: true,
  
  // For backwards compatibility
  supabaseUrl: 'https://cwbywxaafncyplgsrblw.supabase.co',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3Ynl3eGFhZm5jeXBsZ3NyYmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODYzNDYsImV4cCI6MjA3MTk2MjM0Nn0.OANkRlYa6rcCO-Ri3U5h8hfNnYX2-bX_BoalaNfmj9s',
  
  // Master project (auth + metadata)
  supabase: {
    url: 'https://cwbywxaafncyplgsrblw.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3Ynl3eGFhZm5jeXBsZ3NyYmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODYzNDYsImV4cCI6MjA3MTk2MjM0Nn0.OANkRlYa6rcCO-Ri3U5h8hfNnYX2-bX_BoalaNfmj9s'
  }
};
